version: "2"

services:
  jenkins:
    image: ${REGISTRY_URL}/${PROJECT_NAME}
    extends:
      file: common-service.yml
      service: logging
    ports:
    - ${JENKINS_REMOTE_API_PORT}:50000
    - ${JENKINS_HTTP_PORT}:8080
    volumes: 
    - ${JENKINS_HOME}:/var/jenkins_home
    restart: "unless-stopped"